server:
  port: 58192
  context-path: /

# 服务节点,要求分布式下每个节点不同
node: 01

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/os/
  dubbo:
    application:
      name: @project.artifactId@
    registry:
      address: @zookeeper.url@
    scan: org.jeepay.agent
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##

  jackson:
    serialization:
      INDENT_OUTPUT: true
  profiles:
     active: prod

# JWT
jwt:
  cookie: JeePay_Agent_Token
  secret: JeePayGood
  expiration: 604800 # 7天

config:
  payUrl: @pay.site.url@/api

logging:
  file: ./log/jeepay-agent.log
#日志资源
resources:
  #应用名称
  appname: @project.artifactId@
  #日志打印的基础扫描包
  basepackage: org.jeepay
  #日志保存目录
  #logdir: ../logs





